using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StandInstance : MonoBehaviour
{
    public BoxCollider hitCollider;
    public Transform standFront;

    /// <summary>
    /// OnTriggerEnter is called when the Collider other enters the trigger.
    /// </summary>
    /// <param name="other">The other Collider involved in this collision.</param>
    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            hitCollider.enabled = false;
        }
    }

    /// <summary>
    /// OnTriggerExit is called when the Collider other has stopped touching the trigger.
    /// </summary>
    /// <param name="other">The other Collider involved in this collision.</param>
    void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            hitCollider.enabled = true;
        }
    }

}
